spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    #redis连接池
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        min-idle: 5
        max-wait: -1ms