server:
  port: 8090

spring:
  application:
    name: spring-cloud-security-oauth2

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/javakc?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 123456

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/,http://127.0.0.1:8002/eureka/
  instance:
    prefer-ip-address: true